### ISSUE TITLE
It's not an issue, just request

### ISSUE THREAD

**Issue by gibus27** [hyogeunpark/ColorRatingBar#1]
Thank's for your job.
I would like resize ColorRatingBar to besome smaller. How is it possible ?
Thank you again,
Alain

**Comment by hyogeunpark** [comment]
Hi, Alain. It is possible. Try adding style in your xml code.
```xml
<hyogeun.github.com.colorratingbarlib.ColorRatingBar
        style="?android:ratingBarStyleIndicator"
        ...
```
or
```xml
<hyogeun.github.com.colorratingbarlib.ColorRatingBar
        style="?android:ratingBarStyleSmall"
        ...
```
Thank you

Best regards,
Hyogeun

**Comment by gibus27** [comment]
Yes, it's work !

A last question, I would like tu use your colorBar as a viewer only, I've
tried thie :

colorRatingBar.setClickable(false);

But the user can always change the value.

setEnabled(false) works but my colorBar is grey...


Have you a solution ?

Alain


2017-11-13 11:49 GMT+01:00 gpark <notifications@github.com>:

**Comment by hyogeunpark** [comment]
Yes, add this code.

```java
colorRatingBar.setIsIndicator(true); 
```

Thank you
Hyogeun

**Comment by gibus27** [comment]
It's nice.
Thank you very much,
Alain
