### ISSUE TITLE
Handling event setOnRatingBarChangeListener

### ISSUE THREAD

**Issue by niggfreeces** [hyogeunpark/ColorRatingBar#2]
I want to get the value of the rating and display the custom scale e.g. Excellent, Very good, to be displayed in a text view. Is this the right event "setOnRatingBarChangeListener" to get the rating float? Thanks!

**Comment by hyogeunpark** [comment]
Hi, niggfreeces
I'm sorry to reply late.
Answer of your question is yes!
```java
colorRatingBar.setOnRatingBarChangeListener(new RatingBar.OnRatingBarChangeListener() {
            @Override
            public void onRatingChanged(RatingBar ratingBar, float rating, boolean fromUser) {
                // You use the "rating" variable.
            }
        });
```
For more information, [see here](https://developer.android.com/reference/android/widget/RatingBar.OnRatingBarChangeListener)

Thank you!

Best regards,
Hyogeun
